spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: veri-cert
    client: ${CLIENT_URL:http://localhost:4200}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/veri_cert}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}
  hiero:
    account_id: ${HIERO_ACCOUNT_ID}
    private_key: ${HIERO_PRIVATE_KEY}
    network:
      name: ${HIERO_NETWORK:hedera-testnet}
    contract_address: ${CONTRACT_ADDRESS}
